oauth2:
  client-id: client
  client-secret: ttgs123

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB
  profiles:
    include: default
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/db_giasu
    username: root
    password: dungkim
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    url: jdbc:mysql://localhost:3306/mysql
    schemas: db_giasu
    user: root
    password: dungkim
    baseline-on-migrate: true
    check-location: true


file:
  upload-dir: uploads